package writer

import (
	"strings"
	"testing"

	"github.com/front-matter/envy/manifest"
)

func TestGenerateComposeIncludesCommentsAndLists(t *testing.T) {
	m := &manifest.Manifest{
		Meta: manifest.Meta{
			Title:       "Example App",
			Description: "Example description",
			Version:     "v1.2.3",
			Docs:        "https://example.org/docs",
		},
		Services: []manifest.Service{
			{
				Name:        "worker",
				Image:       "ghcr.io/example/worker:latest",
				Description: "Background worker",
				Entrypoint:  []string{"/entrypoint.sh"},
				Command:     []string{"celery", "worker"},
				Sets:      []string{"application"},
			},
		},
		Sets: map[string]manifest.Set{
			"application": {
				Vars: []manifest.Var{{Key: "APP_ENV", Default: "production"}},
			},
		},
	}

	compose := GenerateCompose(m, ComposeOptions{})

	checks := []string{
		"# Generated by envy from env.yaml",
		"# Example App",
		"# Example description",
		"# Version: v1.2.3",
		"# Docs: https://example.org/docs",
		"worker:",
		"    # Background worker",
		"    entrypoint: [/entrypoint.sh]",
		"    command: [celery, worker]",
	}

	for _, check := range checks {
		if !strings.Contains(compose, check) {
			t.Fatalf("compose output missing %q\n%s", check, compose)
		}
	}
}

func TestComposeEnvValue(t *testing.T) {
	tests := []struct {
		name   string
		flavor string
		varDef manifest.Var
		want   string
	}{
		{
			name:   "default editable fallback",
			flavor: "default",
			varDef: manifest.Var{Key: "APP_ENV", Default: "production", Editable: "true"},
			want:   "${APP_ENV:-production}",
		},
		{
			name:   "coolify required editable uses question fallback",
			flavor: "coolify",
			varDef: manifest.Var{Key: "APP_ENV", Default: "production", Required: "true", Editable: "true"},
			want:   "${APP_ENV:?production}",
		},
		{
			name:   "coolify optional editable keeps dash fallback",
			flavor: "coolify",
			varDef: manifest.Var{Key: "APP_ENV", Default: "production", Required: "false", Editable: "true"},
			want:   "${APP_ENV:-production}",
		},
		{
			name:   "default non-editable hardcodes value",
			flavor: "default",
			varDef: manifest.Var{Key: "APP_ENV", Default: "production", Editable: "false"},
			want:   "production",
		},
		{
			name:   "coolify required non-editable hardcodes value",
			flavor: "coolify",
			varDef: manifest.Var{Key: "APP_ENV", Default: "production", Required: "true", Editable: "false"},
			want:   "production",
		},
		{
			name:   "json with variable reference editable",
			flavor: "default",
			varDef: manifest.Var{Key: "APP_JSON", Default: `{"name":"demo"}`, Editable: "true"},
			want:   `${APP_JSON:-{"name":"demo"}}`,
		},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			got := composeEnvValue(test.varDef, test.flavor)
			if got != test.want {
				t.Fatalf("composeEnvValue() = %q, want %q", got, test.want)
			}
		})
	}
}

func TestGenerateComposeIncludesCoolifyLabel(t *testing.T) {
	m := &manifest.Manifest{
		Services: []manifest.Service{{
			Name:   "worker",
			Image:  "ghcr.io/example/worker:latest",
			Sets: []string{"application"},
		}},
		Sets: map[string]manifest.Set{
			"application": {},
		},
	}

	compose := GenerateCompose(m, ComposeOptions{Flavor: "coolify"})

	if !strings.Contains(compose, "    labels:") || !strings.Contains(compose, "      - coolify.managed=true") {
		t.Fatalf("compose output missing coolify label\n%s", compose)
	}
}

func TestGenerateComposeExcludesServices(t *testing.T) {
	m := &manifest.Manifest{
		Services: []manifest.Service{
			{Name: "web", Image: "ghcr.io/example/web:latest", Sets: []string{"application"}},
			{Name: "db", Image: "postgres:17", Sets: []string{"database"}},
		},
		Sets: map[string]manifest.Set{
			"application": {Vars: []manifest.Var{{Key: "APP_ENV", Default: "production"}}},
			"database":    {Vars: []manifest.Var{{Key: "DB_NAME", Default: "app"}}},
		},
	}

	compose := GenerateCompose(m, ComposeOptions{ExcludeServices: []string{"db"}})

	if !strings.Contains(compose, "web:") {
		t.Fatalf("compose output missing included service\n%s", compose)
	}
	if strings.Contains(compose, "db:") {
		t.Fatalf("compose output still contains excluded service\n%s", compose)
	}
}

func TestGenerateComposeExcludesSelectedService(t *testing.T) {
	m := &manifest.Manifest{
		Services: []manifest.Service{
			{Name: "web", Image: "ghcr.io/example/web:latest", Sets: []string{"application"}},
			{Name: "db", Image: "postgres:17", Sets: []string{"database"}},
		},
		Sets: map[string]manifest.Set{
			"application": {Vars: []manifest.Var{{Key: "APP_ENV", Default: "production"}}},
			"database":    {Vars: []manifest.Var{{Key: "DB_NAME", Default: "app"}}},
		},
	}

	compose := GenerateCompose(m, ComposeOptions{ServiceName: "web", ExcludeServices: []string{"web"}})

	if strings.Contains(compose, "web:") {
		t.Fatalf("compose output still contains excluded selected service\n%s", compose)
	}
	if strings.Contains(compose, "db:") {
		t.Fatalf("compose output should not fall back to unrelated services\n%s", compose)
	}
	if !strings.Contains(compose, "services: {}") {
		t.Fatalf("compose output should contain an empty services mapping when all selected services are excluded\n%s", compose)
	}
}

func TestGenerateComposeOmitsSecretVars(t *testing.T) {
	m := &manifest.Manifest{
		Services: []manifest.Service{{
			Name:   "web",
			Image:  "ghcr.io/example/web:latest",
			Sets: []string{"application"},
		}},
		Sets: map[string]manifest.Set{
			"application": {
				Description: "App settings",
				Vars: []manifest.Var{
					{Key: "PUBLIC_URL", Default: "https://example.org"},
					{Key: "SECRET_KEY", Default: "changeme", Secret: "true"},
				},
			},
		},
	}

	compose := GenerateCompose(m, ComposeOptions{})

	if !strings.Contains(compose, "PUBLIC_URL") {
		t.Fatalf("compose output missing non-secret var\n%s", compose)
	}
	if strings.Contains(compose, "SECRET_KEY") {
		t.Fatalf("compose output should omit secret vars\n%s", compose)
	}
	if !strings.Contains(compose, "# ── application") {
		t.Fatalf("compose output missing set header for visible vars\n%s", compose)
	}
	if strings.Contains(compose, "changeme") {
		t.Fatalf("compose output should not contain secret default values\n%s", compose)
	}
}

func TestGenerateComposeEditableAndRequiredOutput(t *testing.T) {
	m := &manifest.Manifest{
		Services: []manifest.Service{{
			Name:   "web",
			Image:  "ghcr.io/example/web:latest",
			Sets: []string{"application"},
		}},
		Sets: map[string]manifest.Set{
			"application": {
				Vars: []manifest.Var{
					{Key: "EDITABLE_OPT", Default: "opt", Editable: "true", Required: "false"},
					{Key: "EDITABLE_REQ", Default: "req", Editable: "true", Required: "true"},
					{Key: "LOCKED_REQ", Default: "locked", Editable: "false", Required: "true"},
				},
			},
		},
	}

	defaultCompose := GenerateCompose(m, ComposeOptions{Flavor: "default"})
	if !strings.Contains(defaultCompose, "EDITABLE_OPT: \"${EDITABLE_OPT:-opt}\"") {
		t.Fatalf("default flavor missing editable optional fallback\n%s", defaultCompose)
	}
	if !strings.Contains(defaultCompose, "EDITABLE_REQ: \"${EDITABLE_REQ:-req}\"") {
		t.Fatalf("default flavor missing editable required fallback\n%s", defaultCompose)
	}
	if !strings.Contains(defaultCompose, "LOCKED_REQ: \"locked\"") {
		t.Fatalf("default flavor should hardcode non-editable var\n%s", defaultCompose)
	}

	coolifyCompose := GenerateCompose(m, ComposeOptions{Flavor: "coolify"})
	if !strings.Contains(coolifyCompose, "EDITABLE_OPT: \"${EDITABLE_OPT:-opt}\"") {
		t.Fatalf("coolify flavor missing editable optional fallback\n%s", coolifyCompose)
	}
	if !strings.Contains(coolifyCompose, "EDITABLE_REQ: \"${EDITABLE_REQ:?req}\"") {
		t.Fatalf("coolify flavor should use :? for editable required vars\n%s", coolifyCompose)
	}
	if !strings.Contains(coolifyCompose, "LOCKED_REQ: \"locked\"") {
		t.Fatalf("coolify flavor should hardcode non-editable var\n%s", coolifyCompose)
	}
}
