package writer

import (
	"bytes"
	"fmt"
	"strings"

	"github.com/front-matter/envy/manifest"
	"gopkg.in/yaml.v3"
)

// ComposeOptions controls Docker Compose generation.
type ComposeOptions struct {
	ServiceName     string
	ExcludeServices []string
	Flavor          string
}

// GenerateCompose renders a compose.yaml with one service block per service defined
// in the manifest.  Each block contains only the env vars belonging to the sets
// listed for that service.  Pass ServiceName to emit a single service only.
func GenerateCompose(m *manifest.Manifest, opts ComposeOptions) string {
	filter := strings.TrimSpace(opts.ServiceName)

	flavor := strings.TrimSpace(opts.Flavor)
	if flavor == "" {
		flavor = "default"
	}

	services := m.Services
	if filter != "" {
		for _, svc := range services {
			if svc.Name == filter {
				services = []manifest.Service{svc}
				break
			}
		}
	}

	excluded := make(map[string]bool)
	for _, name := range opts.ExcludeServices {
		name = strings.TrimSpace(name)
		if name == "" {
			continue
		}
		excluded[name] = true
	}

	filteredServices := make([]manifest.Service, 0, len(services))
	for _, svc := range services {
		if excluded[svc.Name] {
			continue
		}
		filteredServices = append(filteredServices, svc)
	}
	services = filteredServices

	var sb strings.Builder
	sb.WriteString("# Generated by envy from env.yaml\n")
	writeComposeHeaderMeta(&sb, m)
	if flavor == "coolify" {
		sb.WriteString("# Flavor: coolify\n")
	}
	document, err := buildComposeDocument(m, services, flavor)
	if err != nil {
		return sb.String()
	}

	sb.Write(document)
	return sb.String()
}

func writeComposeHeaderMeta(sb *strings.Builder, m *manifest.Manifest) {
	writeCommentLines(sb, m.Meta.Title)
	writeCommentLines(sb, m.Meta.Description)

	version := strings.TrimSpace(m.Meta.VersionLabel())
	if version != "" {
		sb.WriteString(fmt.Sprintf("# Version: %s\n", version))
	}

	docs := strings.TrimSpace(m.Meta.Docs)
	if docs != "" {
		sb.WriteString(fmt.Sprintf("# Docs: %s\n", docs))
	}
}

func writeCommentLines(sb *strings.Builder, value string) {
	value = strings.TrimSpace(value)
	if value == "" {
		return
	}

	for _, line := range strings.Split(value, "\n") {
		line = strings.TrimSpace(line)
		if line == "" {
			continue
		}
		sb.WriteString(fmt.Sprintf("# %s\n", line))
	}
}

func buildComposeDocument(m *manifest.Manifest, services []manifest.Service, flavor string) ([]byte, error) {
	servicesNode := &yaml.Node{Kind: yaml.MappingNode}

	for _, svc := range services {
		appendServiceNode(servicesNode, svc, m.VarsForServiceBySet(svc.Name), flavor)
	}

	root := &yaml.Node{Kind: yaml.MappingNode}
	appendMappingNode(root, "services", servicesNode)

	document := &yaml.Node{Kind: yaml.DocumentNode, Content: []*yaml.Node{root}}

	var buf bytes.Buffer
	encoder := yaml.NewEncoder(&buf)
	encoder.SetIndent(2)
	if err := encoder.Encode(document); err != nil {
		return nil, err
	}
	if err := encoder.Close(); err != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

func appendServiceNode(parent *yaml.Node, svc manifest.Service, sets []manifest.SetVars, flavor string) {
	serviceKey := scalarNode(svc.Name, 0)
	serviceValue := &yaml.Node{Kind: yaml.MappingNode}

	image := composeServiceImage(svc)
	platform := composeServicePlatform(svc)

	appendMappingScalar(serviceValue, "image", image, 0)
	appendMappingScalar(serviceValue, "platform", platform, 0)
	appendMappingSequence(serviceValue, "entrypoint", svc.Entrypoint, yaml.FlowStyle)
	appendMappingSequence(serviceValue, "command", svc.Command, yaml.FlowStyle)

	if flavor == "coolify" {
		appendMappingSequence(serviceValue, "labels", []string{"coolify.managed=true"}, 0)
	}

	environment := composeEnvironmentNodeBySet(sets, flavor)
	if len(environment.Content) > 0 {
		appendMappingNode(serviceValue, "environment", environment)
	}

	if comment := composeComment(svc.Description); comment != "" && len(serviceValue.Content) > 0 {
		serviceValue.Content[0].HeadComment = comment
	}

	parent.Content = append(parent.Content, serviceKey, serviceValue)
}

func composeServiceImage(svc manifest.Service) string {
	image := strings.TrimSpace(svc.Image)
	if image == "" {
		return "alpine:latest"
	}
	return image
}

func composeServicePlatform(svc manifest.Service) string {
	platform := strings.TrimSpace(svc.Platform)
	if platform == "" {
		return "linux/amd64"
	}
	return platform
}

func composeEnvironmentNodeBySet(sets []manifest.SetVars, flavor string) *yaml.Node {
	environment := &yaml.Node{Kind: yaml.MappingNode}
	for _, setVars := range sets {
		visibleVars := make([]manifest.Var, 0, len(setVars.Vars))
		for _, v := range setVars.Vars {
			if v.IsSecret() {
				continue
			}
			visibleVars = append(visibleVars, v)
		}

		if len(visibleVars) == 0 {
			continue
		}
		dashes := strings.Repeat("─", dashWidth(setVars.SetKey))
		setHeader := fmt.Sprintf("# ── %s %s", setVars.SetKey, dashes)
		if desc := strings.TrimSpace(setVars.Description); desc != "" {
			setHeader += "\n# " + desc
		}
		first := true
		for _, v := range visibleVars {
			key := scalarNode(v.Key, 0)
			var headComment string
			if first {
				headComment = setHeader
				first = false
			}
			if desc := strings.TrimSpace(v.Description); desc != "" {
				line := "# " + strings.ReplaceAll(desc, "\n", " ")
				if headComment != "" {
					headComment += "\n" + line
				} else {
					headComment = line
				}
			}
			if ex := strings.TrimSpace(v.Example); ex != "" {
				line := "# Example: " + ex
				if headComment != "" {
					headComment += "\n" + line
				} else {
					headComment = line
				}
			}
			if headComment != "" {
				key.HeadComment = headComment
			}
			environment.Content = append(environment.Content,
				key,
				scalarNode(composeEnvValue(v, flavor), yaml.DoubleQuotedStyle),
			)
		}
	}
	return environment
}

func composeEnvValue(v manifest.Var, flavor string) string {
	defaultVal := v.DefaultString()
	if v.IsReadonly() {
		return defaultVal
	}

	if flavor == "coolify" && v.IsRequired() {
		return fmt.Sprintf("${%s:?%s}", v.Key, defaultVal)
	}

	return fmt.Sprintf("${%s:-%s}", v.Key, defaultVal)
}

func appendMappingScalar(parent *yaml.Node, key, value string, style yaml.Style) {
	parent.Content = append(parent.Content,
		scalarNode(key, 0),
		scalarNode(value, style),
	)
}

func appendMappingNode(parent *yaml.Node, key string, value *yaml.Node) {
	parent.Content = append(parent.Content, scalarNode(key, 0), value)
}

func appendMappingSequence(parent *yaml.Node, key string, values []string, style yaml.Style) {
	sequence := &yaml.Node{Kind: yaml.SequenceNode, Style: style}
	for _, value := range values {
		value = strings.TrimSpace(value)
		if value == "" {
			continue
		}
		sequence.Content = append(sequence.Content, scalarNode(value, 0))
	}

	if len(sequence.Content) == 0 {
		return
	}

	appendMappingNode(parent, key, sequence)
}

func scalarNode(value string, style yaml.Style) *yaml.Node {
	return &yaml.Node{Kind: yaml.ScalarNode, Value: value, Style: style}
}

func composeComment(value string) string {
	value = strings.TrimSpace(value)
	if value == "" {
		return ""
	}

	var lines []string
	for _, line := range strings.Split(value, "\n") {
		line = strings.TrimSpace(line)
		if line == "" {
			continue
		}
		lines = append(lines, line)
	}

	return strings.Join(lines, "\n")
}
