package reader

import (
	types "github.com/compose-spec/compose-go/v2/types"

	"github.com/front-matter/envy/compose"
)

// Merge combines multiple manifests into a single compose.
// Services are appended, sets are merged with later sources overwriting earlier ones.
// Variables within sets are merged with later sources providing defaults for missing vars.
func Merge(manifests ...*compose.Project) *compose.Project {
	if len(manifests) == 0 {
		return &compose.Project{
			Meta:     compose.Meta{Title: "Merged Manifest", LanguageCode: "en-US", Version: "v1"},
			Services: map[string]compose.Service{},
			Sets:     make(map[string]compose.Set),
		}
	}

	if len(manifests) == 1 {
		return manifests[0]
	}

	// Start with the first manifest as base
	merged := &compose.Project{
		Meta: compose.Meta{
			Title:        "Merged Manifest",
			Description:  "Generated by merging multiple sources",
			LanguageCode: "en-US",
			Version:      "v1",
		},
		Services: make(map[string]compose.Service, len(manifests[0].Services)),
		Sets:     make(map[string]compose.Set),
	}

	for name, service := range manifests[0].Services {
		merged.Services[name] = service
	}

	// Copy sets from first manifest
	for key, set := range manifests[0].Sets {
		merged.Sets[key] = set
	}

	// Merge subsequent manifests
	for i := 1; i < len(manifests); i++ {
		m := manifests[i]

		// Merge services with later manifests taking precedence.
		for name, service := range m.Services {
			merged.Services[name] = service
		}

		// Merge sets: combine variables with later sources taking precedence
		for setKey, set := range m.Sets {
			// Special case: if this is the "env" set, filter out vars that already exist in other sets
			if setKey == "env" {
				otherKeys := make(map[string]bool)
				for gk, g := range merged.Sets {
					if gk != "env" {
						for key := range g.Vars() {
							otherKeys[key] = true
						}
					}
				}
				// Filter env vars to exclude those already in other sets.
				filteredVars := types.MappingWithEquals{}
				for key, value := range set.Vars() {
					if !otherKeys[key] {
						filteredVars[key] = value
					}
				}
				set.SetVars(filteredVars)
			}

			if existing, ok := merged.Sets[setKey]; ok {
				// Set already exists, merge variables.
				vars := mergeVars(existing.Vars(), set.Vars())
				existing.SetVars(vars)
				// Update merged sets with the merged set.
				merged.Sets[setKey] = existing
			} else {
				// New set, add it.
				merged.Sets[setKey] = set
			}
		}
	}

	return merged
}

// mergeVars combines two var maps, preferring the latter source for conflicts.
func mergeVars(base, overlay types.MappingWithEquals) types.MappingWithEquals {
	varMap := types.MappingWithEquals{}
	for key, value := range base {
		if value == nil {
			varMap[key] = nil
			continue
		}
		v := *value
		varMap[key] = &v
	}

	for key, value := range overlay {
		if value == nil {
			varMap[key] = nil
			continue
		}
		v := *value
		varMap[key] = &v
	}

	return varMap
}
