package reader

import (
	"sort"

	"github.com/front-matter/envy/manifest"
)

// Merge combines multiple manifests into a single manifest.
// Services are appended, sets are merged with later sources overwriting earlier ones.
// Variables within sets are merged with later sources providing defaults for missing vars.
func Merge(manifests ...*manifest.Manifest) *manifest.Manifest {
	if len(manifests) == 0 {
		return &manifest.Manifest{
			Meta:     manifest.Meta{Title: "Merged Manifest", LanguageCode: "en-US", Version: "v1"},
			Services: []manifest.Service{},
			Sets:     make(map[string]manifest.Set),
		}
	}

	if len(manifests) == 1 {
		return manifests[0]
	}

	// Start with the first manifest as base
	merged := &manifest.Manifest{
		Meta: manifest.Meta{
			Title:        "Merged Manifest",
			Description:  "Generated by merging multiple sources",
			LanguageCode: "en-US",
			Version:      "v1",
		},
		Services: make([]manifest.Service, len(manifests[0].Services)),
		Sets:     make(map[string]manifest.Set),
	}

	copy(merged.Services, manifests[0].Services)

	// Copy sets from first manifest
	for key, set := range manifests[0].Sets {
		merged.Sets[key] = set
	}

	// Merge subsequent manifests
	for i := 1; i < len(manifests); i++ {
		m := manifests[i]

		// Append services
		merged.Services = append(merged.Services, m.Services...)

		// Merge sets: combine variables with later sources taking precedence
		for setKey, set := range m.Sets {
			// Special case: if this is the "env" set, filter out vars that already exist in other sets
			if setKey == "env" {
				otherKeys := make(map[string]bool)
				for gk, g := range merged.Sets {
					if gk != "env" {
						for _, v := range g.Vars {
							otherKeys[v.Key] = true
						}
					}
				}
				// Filter env vars to exclude those already in other sets.
				var filteredVars []manifest.Var
				for _, v := range set.Vars {
					if !otherKeys[v.Key] {
						filteredVars = append(filteredVars, v)
					}
				}
				set.Vars = filteredVars
			}

			if existing, ok := merged.Sets[setKey]; ok {
				// Set already exists, merge variables.
				vars := mergeVars(existing.Vars, set.Vars)
				existing.Vars = vars
				// Update merged sets with the merged set.
				merged.Sets[setKey] = existing
			} else {
				// New set, add it.
				merged.Sets[setKey] = set
			}
		}
	}

	return merged
}

// mergeVars combines two variable lists, preferring the latter source for conflicts.
// Returns a sorted list of merged variables.
func mergeVars(base, overlay []manifest.Var) []manifest.Var {
	// Create a map from base vars for quick lookup
	varMap := make(map[string]manifest.Var)
	for _, v := range base {
		varMap[v.Key] = v
	}

	// Overlay with later vars
	for _, v := range overlay {
		varMap[v.Key] = v
	}

	// Sort by key and return as slice
	keys := make([]string, 0, len(varMap))
	for k := range varMap {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	result := make([]manifest.Var, 0, len(varMap))
	for _, k := range keys {
		result = append(result, varMap[k])
	}

	return result
}
