package reader

import (
	"sort"

	"github.com/front-matter/envy/manifest"
)

// Merge combines multiple manifests into a single manifest.
// Services are appended, groups are merged with later sources overwriting earlier ones.
// Variables within groups are merged with later sources providing defaults for missing vars.
func Merge(manifests ...*manifest.Manifest) *manifest.Manifest {
	if len(manifests) == 0 {
		return &manifest.Manifest{
			Meta:     manifest.Meta{Name: "Merged Manifest", Version: "v1"},
			Services: []manifest.Service{},
			Groups:   make(map[string]manifest.Group),
		}
	}

	if len(manifests) == 1 {
		return manifests[0]
	}

	// Start with the first manifest as base
	merged := &manifest.Manifest{
		Meta: manifest.Meta{
			Name:        "Merged Manifest",
			Description: "Generated by merging multiple sources",
			Version:     "v1",
		},
		Services: make([]manifest.Service, len(manifests[0].Services)),
		Groups:   make(map[string]manifest.Group),
	}

	copy(merged.Services, manifests[0].Services)

	// Copy groups from first manifest
	for key, group := range manifests[0].Groups {
		merged.Groups[key] = group
	}

	// Merge subsequent manifests
	for i := 1; i < len(manifests); i++ {
		m := manifests[i]

		// Append services
		merged.Services = append(merged.Services, m.Services...)

		// Merge groups: combine variables with later sources taking precedence
		for groupKey, group := range m.Groups {
			// Special case: if this is the "env" group, filter out vars that already exist in other groups
			if groupKey == "env" {
				otherKeys := make(map[string]bool)
				for gk, g := range merged.Groups {
					if gk != "env" {
						for _, v := range g.Vars {
							otherKeys[v.Key] = true
						}
					}
				}
				// Filter env vars to exclude those already in other groups
				var filteredVars []manifest.Var
				for _, v := range group.Vars {
					if !otherKeys[v.Key] {
						filteredVars = append(filteredVars, v)
					}
				}
				group.Vars = filteredVars
			}

			if existing, ok := merged.Groups[groupKey]; ok {
				// Group already exists, merge variables
				vars := mergeVars(existing.Vars, group.Vars)
				existing.Vars = vars
				// Update merged groups with the merged group
				merged.Groups[groupKey] = existing
			} else {
				// New group, add it
				merged.Groups[groupKey] = group
			}
		}
	}

	return merged
}

// mergeVars combines two variable lists, preferring the latter source for conflicts.
// Returns a sorted list of merged variables.
func mergeVars(base, overlay []manifest.Var) []manifest.Var {
	// Create a map from base vars for quick lookup
	varMap := make(map[string]manifest.Var)
	for _, v := range base {
		varMap[v.Key] = v
	}

	// Overlay with later vars
	for _, v := range overlay {
		varMap[v.Key] = v
	}

	// Sort by key and return as slice
	keys := make([]string, 0, len(varMap))
	for k := range varMap {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	result := make([]manifest.Var, 0, len(varMap))
	for _, k := range keys {
		result = append(result, varMap[k])
	}

	return result
}
